# Generated by Django 4.2.4 on 2023-09-14 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'constituencys',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200, null=True)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constituency')),
            ],
            options={
                'db_table': 'polling_stations',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.district'),
        ),
    ]
