# Generated by Django 4.2.4 on 2023-09-15 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstation',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='polling_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
