# Generated by Django 4.2.4 on 2023-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pollingstation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstation',
            name='is_uploded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
