# Generated by Django 4.2.4 on 2023-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
