# Generated by Django 4.2.4 on 2023-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='comments',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='feed',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='mobile_no',
            field=models.CharField(max_length=150),
        ),
    ]
