# Generated by Django 4.2.4 on 2023-09-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('master', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='polling_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pollingstation'),
        ),
    ]
