# Generated by Django 4.2.4 on 2023-09-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_voter_polling_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
