# Generated by Django 4.2.4 on 2023-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_report_image_alter_report_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='report_image',
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter_selfie',
            field=models.FileField(blank=True, null=True, upload_to='uploads/reports'),
        ),
    ]
