# Generated by Django 4.2.4 on 2023-08-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_feedcomment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedcomment',
            table='feed_comments',
        ),
        migrations.AlterModelTable(
            name='feedlike',
            table='feed_likes',
        ),
    ]
