# Generated by Django 4.2.4 on 2023-08-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_feedcomment_table_alter_feedlike_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
    ]
