# Generated by Django 4.2.4 on 2023-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_report_mla_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
