# Generated by Django 4.2.4 on 2023-08-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_feed_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlike',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='master.feed'),
        ),
    ]
