# Generated by Django 4.2.4 on 2023-09-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pollingstation_is_uploded'),
        ('master', '0006_voter_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.constituency'),
        ),
        migrations.AddField(
            model_name='voter',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='booth_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='polling_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pollingstation'),
        ),
    ]
