# Generated by Django 4.2.4 on 2023-09-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_voter_constituency_voter_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
