# Generated by Django 4.2.4 on 2023-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('agent', 'agent'), ('voter', 'voter')], max_length=50, null=True),
        ),
    ]
