# Generated by Django 4.2.4 on 2023-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fcm_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
