# Generated by Django 4.2.4 on 2023-09-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_mla'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mla',
            field=models.BooleanField(null=True),
        ),
    ]
